### ISSUE TITLE
Cannot find module '@linvix-sistemas/react-native-escpos-buffer'

### ISSUE THREAD

**Issue by mokaty1818795** [linvix-sistemas/react-native-bluetooth-printer#1]
I am trying to follow the example  made and currently facing an  issue.

Cannot find module '@linvix-sistemas/react-native-escpos-buffer' or its corresponding type declarations.ts(2307)

**Comment by cristiano-linvix** [comment]
This dependency is from the example project, and is only used to demonstrate the printing of a test.

Have you installed the example project's dependencies?

```sh
cd example && yarn install
```

**Comment by mokaty1818795** [comment]
I was doing the test app so i realized that the other dependency comes from a different package
I was able to Solve it.

**Comment by cristiano-linvix** [comment]
Awesome!
