### ISSUE TITLE
[Error: read failed, socket might closed or timeout, read ret: -1]

### ISSUE THREAD

**Issue by ALTHGA** [linvix-sistemas/react-native-bluetooth-printer#2]
Quando vou conectar diz: [Error: read failed, socket might closed or timeout, read ret: -1]

Impressora: MPT-II

**Comment by cristiano-linvix** [comment]
Olá, preciso de mais informações para poder analisar o caso.

A impressora estava em modo de pareamento?

Forneça também o logcat do Android para analisar se tem algum erro que nos ajude a identificar a causa.

**Comment by cristiano-linvix** [comment]
Fechando por inatividade.
